# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
trigger:
- main

pool:
  name: SelfHostedPool # Replace with the name of your agent pool (e.g., SelfHostedPool)

variables:
  buildConfiguration: 'Release'

steps:
# Step 1: Checkout the Code
- task: Checkout@1
  displayName: 'Checkout source code'

# Step 2: Set Up .NET Core
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '7.x' # Replace with the .NET version your project uses (e.g., 6.x, 7.x, etc.)

# Step 3: Restore Dependencies
- script: dotnet restore
  displayName: 'Restore dependencies'

# Step 4: Build the Project
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build the project'

# Step 5: Run Tests (Optional)
- script: dotnet test --no-build --verbosity normal
  displayName: 'Run tests'

# Step 6: Publish Artifacts
- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the project'

# Step 7: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
.
